#!/usr/bin/env bash
#Reescribiendo IP de localhsot

cp /etc/hosts /etc/hosts.bak
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sed -i 's/157.240.11.35 facebook/8.8.8.8 facebook.com/' /etc/hosts
